### ISSUE TITLE
DEBUG_LOG: unbound variable

### ISSUE THREAD

**Issue by fpedroza** [martinburger/bash-common-helpers#1]
When using this locally on my mac, I see this error when running without the debug flag.

    DEBUG_LOG: unbound variable

**Comment by martinburger** [comment]
I assume that one of your scripts references the _uninitialized_ variable `DEBUG_LOG` _after_ having loaded my library and having called helper function `cmn_init`.

The latter function includes `set -o nounset` which will exit your script if you try to use an uninitialized variable.

You can find more information about the motivation of this at https://www.davidpashley.com/articles/writing-robust-shell-scripts/.

**Comment by fpedroza** [comment]
The thing is though that it's the reference in the bash-common-helpers.sh cmn_debug function that is causing the error.

**Comment by martinburger** [comment]
I cannot find any references either to a function called `cmn_debug` or to a variable called `DEBUG_LOG` in my code. However, it might be that I'm missing something here.

**Comment by fpedroza** [comment]
Oh geeze... my bad. This is something I have locally. I've found it very helpful, but clearly this in on my end. Here it is FYI

```
#------------------------------------------------------------------------------
# debug message ...
#
# Log a debug message.
#
# Example:
#   DEBUG_LOG=1 ./script.sh
#
cmn_debug() { 
    ((DEBUG_LOG)) && echo "--- $*"; 
    :  # no-op
}
```
